In [1]:
import pickle

In [2]:
feature_list = pickle.load(open('embeddings.pkl','rb'))
print(feature_list)

[array([0.01857485, 0.06382134, 0.00820326, ..., 0.00458092, 0.02108615,
       0.01906079], dtype=float32), array([0.0122906 , 0.07299963, 0.        , ..., 0.0074838 , 0.00676469,
       0.03499291], dtype=float32), array([0.        , 0.07435312, 0.        , ..., 0.        , 0.00694484,
       0.04765104], dtype=float32), array([0.01130287, 0.10467432, 0.01115361, ..., 0.        , 0.01109497,
       0.02144955], dtype=float32), array([0.        , 0.04444405, 0.01576786, ..., 0.02554569, 0.00918568,
       0.04919996], dtype=float32), array([0.        , 0.07238507, 0.00172422, ..., 0.01341863, 0.00029398,
       0.02861209], dtype=float32), array([0.00945578, 0.05666594, 0.        , ..., 0.01248662, 0.01578214,
       0.03142292], dtype=float32), array([0.01187079, 0.0447516 , 0.        , ..., 0.00589557, 0.00895464,
       0.02920656], dtype=float32), array([0.00533218, 0.06448317, 0.        , ..., 0.        , 0.00764496,
       0.02994085], dtype=float32), array([0.00661074, 0.067093

In [3]:
import numpy as np
print(np.array(feature_list).shape)

(1050, 2048)


In [4]:
feature_list = np.array(pickle.load(open('embeddings.pkl','rb')))
print(feature_list)

[[0.01857485 0.06382134 0.00820326 ... 0.00458092 0.02108615 0.01906079]
 [0.0122906  0.07299963 0.         ... 0.0074838  0.00676469 0.03499291]
 [0.         0.07435312 0.         ... 0.         0.00694484 0.04765104]
 ...
 [0.         0.01414168 0.0014997  ... 0.00310044 0.00992962 0.03982098]
 [0.         0.01610788 0.         ... 0.00369905 0.02696848 0.03585126]
 [0.         0.04423349 0.01095894 ... 0.00043234 0.         0.02105376]]


In [5]:
filenames = pickle.load(open('filenames.pkl','rb'))

In [6]:
!pip install opencv-python

You should consider upgrading via the 'C:\Users\ravid\anaconda3\python.exe -m pip install --upgrade pip' command.


In [7]:
import pickle
import tensorflow
import numpy as np
from numpy.linalg import norm
from tensorflow.keras.preprocessing import image
from tensorflow.keras.layers import GlobalMaxPooling2D
from tensorflow.keras.applications.resnet50 import ResNet50,preprocess_input
from sklearn.neighbors import NearestNeighbors
import cv2
from tkinter import filedialog
from tkinter import *

feature_list = np.array(pickle.load(open('embeddings.pkl','rb')))
filenames = pickle.load(open('filenames.pkl','rb'))

model = ResNet50(weights='imagenet',include_top=False,input_shape=(224,224,3))
model.trainable = False

model = tensorflow.keras.Sequential([
    model,
    GlobalMaxPooling2D()
])

root = Tk()
root.filename =  filedialog.askopenfilename(initialdir = "/",title = "Select file",filetypes = (("jpeg files","*.jpg"),("all files","*.*")))
img = image.load_img(root.filename,target_size=(224,224))
img_array = image.img_to_array(img)
expanded_img_array = np.expand_dims(img_array, axis=0)
preprocessed_img = preprocess_input(expanded_img_array)
result = model.predict(preprocessed_img).flatten()
normalized_result = result / norm(result)

neighbors = NearestNeighbors(n_neighbors=11,algorithm='brute',metric='euclidean')
neighbors.fit(feature_list)

distances,indices = neighbors.kneighbors([normalized_result])

print(indices)

for file in indices[0][1:11]:
    temp_img = cv2.imread(filenames[file])
    cv2.imshow('output',cv2.resize(temp_img,(512,512)))
    cv2.waitKey(0)

[[  1 702  31 221 351  39  35 555  12 726 220]]
